version = 1

test_patterns = ["**/test/**"]

exclude_patterns = ["**/subMultiModuleWithErrors/**"]

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "8"

[[analyzers]]
name = "secrets"
enabled = true

[[transformers]]
name = "google-java-format"
enabled = true
